# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d4106ea8d09abf2388490028edd46811f29ac1c6cde7ea961344358bf094d5290bbb351efcf1d4a9ab473ccba359fa88f4975d38fb77ba6c331d026a3e59968

test:
  secret_key_base: 8834df6796b20269c177d7f3f0efa48aeaab9083bd7e3fbe92d62e5c6b5f9520d06d171cc82ab0fa52097986b6e967195168cf66cfec797920f6ad6fe0a462d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
